/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JudgeRouteImport } from './routes/judge'
import { Route as JudgeLoginRouteImport } from './routes/judge-login'
import { Route as OrganizerLoginRouteImport } from './routes/organizer-login'
import { Route as ParticipantRouteImport } from './routes/participant'
import { Route as JudgeIndexRouteImport } from './routes/judge.index'
import { Route as JudgeClustersIndexRouteImport } from './routes/judge.clusters.index'
import { Route as JudgeClustersIdRouteImport } from './routes/judge.clusters.$id'
import { Route as JudgeSubmissionsIndexRouteImport } from './routes/judge.submissions.index'
import { Route as JudgeSubmissionsIdRouteImport } from './routes/judge.submissions.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeRoute = JudgeRouteImport.update({
  id: '/judge',
  path: '/judge',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeLoginRoute = JudgeLoginRouteImport.update({
  id: '/judge-login',
  path: '/judge-login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerLoginRoute = OrganizerLoginRouteImport.update({
  id: '/organizer-login',
  path: '/organizer-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ParticipantRoute = ParticipantRouteImport.update({
  id: '/participant',
  path: '/participant',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeIndexRoute = JudgeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JudgeRoute,
} as any)
const JudgeClustersIndexRoute = JudgeClustersIndexRouteImport.update({
  id: '/clusters/',
  path: '/clusters/',
  getParentRoute: () => JudgeRoute,
} as any)
const JudgeClustersIdRoute = JudgeClustersIdRouteImport.update({
  id: '/clusters/$id',
  path: '/clusters/$id',
  getParentRoute: () => JudgeRoute,
} as any)
const JudgeSubmissionsIndexRoute = JudgeSubmissionsIndexRouteImport.update({
  id: '/submissions/',
  path: '/submissions/',
  getParentRoute: () => JudgeRoute,
} as any)
const JudgeSubmissionsIdRoute = JudgeSubmissionsIdRouteImport.update({
  id: '/submissions/$id',
  path: '/submissions/$id',
  getParentRoute: () => JudgeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/judge': typeof JudgeRouteWithChildren
  '/judge-login': typeof JudgeLoginRoute
  '/organizer-login': typeof OrganizerLoginRoute
  '/participant': typeof ParticipantRoute
  '/judge/': typeof JudgeIndexRoute
  '/judge/clusters/$id': typeof JudgeClustersIdRoute
  '/judge/submissions/$id': typeof JudgeSubmissionsIdRoute
  '/judge/clusters/': typeof JudgeClustersIndexRoute
  '/judge/submissions/': typeof JudgeSubmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/judge-login': typeof JudgeLoginRoute
  '/organizer-login': typeof OrganizerLoginRoute
  '/participant': typeof ParticipantRoute
  '/judge': typeof JudgeIndexRoute
  '/judge/clusters/$id': typeof JudgeClustersIdRoute
  '/judge/submissions/$id': typeof JudgeSubmissionsIdRoute
  '/judge/clusters': typeof JudgeClustersIndexRoute
  '/judge/submissions': typeof JudgeSubmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/judge': typeof JudgeRouteWithChildren
  '/judge-login': typeof JudgeLoginRoute
  '/organizer-login': typeof OrganizerLoginRoute
  '/participant': typeof ParticipantRoute
  '/judge/': typeof JudgeIndexRoute
  '/judge/clusters/$id': typeof JudgeClustersIdRoute
  '/judge/submissions/$id': typeof JudgeSubmissionsIdRoute
  '/judge/clusters/': typeof JudgeClustersIndexRoute
  '/judge/submissions/': typeof JudgeSubmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/judge'
    | '/judge-login'
    | '/organizer-login'
    | '/participant'
    | '/judge/'
    | '/judge/clusters/$id'
    | '/judge/submissions/$id'
    | '/judge/clusters/'
    | '/judge/submissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/judge-login'
    | '/organizer-login'
    | '/participant'
    | '/judge'
    | '/judge/clusters/$id'
    | '/judge/submissions/$id'
    | '/judge/clusters'
    | '/judge/submissions'
  id:
    | '__root__'
    | '/'
    | '/judge'
    | '/judge-login'
    | '/organizer-login'
    | '/participant'
    | '/judge/'
    | '/judge/clusters/$id'
    | '/judge/submissions/$id'
    | '/judge/clusters/'
    | '/judge/submissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JudgeRoute: typeof JudgeRouteWithChildren
  JudgeLoginRoute: typeof JudgeLoginRoute
  OrganizerLoginRoute: typeof OrganizerLoginRoute
  ParticipantRoute: typeof ParticipantRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge': {
      id: '/judge'
      path: '/judge'
      fullPath: '/judge'
      preLoaderRoute: typeof JudgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge-login': {
      id: '/judge-login'
      path: '/judge-login'
      fullPath: '/judge-login'
      preLoaderRoute: typeof JudgeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer-login': {
      id: '/organizer-login'
      path: '/organizer-login'
      fullPath: '/organizer-login'
      preLoaderRoute: typeof OrganizerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/participant': {
      id: '/participant'
      path: '/participant'
      fullPath: '/participant'
      preLoaderRoute: typeof ParticipantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge/': {
      id: '/judge/'
      path: '/'
      fullPath: '/judge/'
      preLoaderRoute: typeof JudgeIndexRouteImport
      parentRoute: typeof JudgeRoute
    }
    '/judge/clusters/': {
      id: '/judge/clusters/'
      path: '/clusters'
      fullPath: '/judge/clusters/'
      preLoaderRoute: typeof JudgeClustersIndexRouteImport
      parentRoute: typeof JudgeRoute
    }
    '/judge/clusters/$id': {
      id: '/judge/clusters/$id'
      path: '/clusters/$id'
      fullPath: '/judge/clusters/$id'
      preLoaderRoute: typeof JudgeClustersIdRouteImport
      parentRoute: typeof JudgeRoute
    }
    '/judge/submissions/': {
      id: '/judge/submissions/'
      path: '/submissions'
      fullPath: '/judge/submissions/'
      preLoaderRoute: typeof JudgeSubmissionsIndexRouteImport
      parentRoute: typeof JudgeRoute
    }
    '/judge/submissions/$id': {
      id: '/judge/submissions/$id'
      path: '/submissions/$id'
      fullPath: '/judge/submissions/$id'
      preLoaderRoute: typeof JudgeSubmissionsIdRouteImport
      parentRoute: typeof JudgeRoute
    }
  }
}

interface JudgeRouteChildren {
  JudgeIndexRoute: typeof JudgeIndexRoute
  JudgeClustersIdRoute: typeof JudgeClustersIdRoute
  JudgeSubmissionsIdRoute: typeof JudgeSubmissionsIdRoute
  JudgeClustersIndexRoute: typeof JudgeClustersIndexRoute
  JudgeSubmissionsIndexRoute: typeof JudgeSubmissionsIndexRoute
}

const JudgeRouteChildren: JudgeRouteChildren = {
  JudgeIndexRoute: JudgeIndexRoute,
  JudgeClustersIdRoute: JudgeClustersIdRoute,
  JudgeSubmissionsIdRoute: JudgeSubmissionsIdRoute,
  JudgeClustersIndexRoute: JudgeClustersIndexRoute,
  JudgeSubmissionsIndexRoute: JudgeSubmissionsIndexRoute,
}

const JudgeRouteWithChildren = JudgeRoute._addFileChildren(JudgeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JudgeRoute: JudgeRouteWithChildren,
  JudgeLoginRoute: JudgeLoginRoute,
  OrganizerLoginRoute: OrganizerLoginRoute,
  ParticipantRoute: ParticipantRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
