/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JudgeLoginRouteImport } from './routes/judge-login'
import { Route as OrganizerLoginRouteImport } from './routes/organizer-login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeLoginRoute = JudgeLoginRouteImport.update({
  id: '/judge-login',
  path: '/judge-login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerLoginRoute = OrganizerLoginRouteImport.update({
  id: '/organizer-login',
  path: '/organizer-login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/judge-login': typeof JudgeLoginRoute
  '/organizer-login': typeof OrganizerLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/judge-login': typeof JudgeLoginRoute
  '/organizer-login': typeof OrganizerLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/judge-login': typeof JudgeLoginRoute
  '/organizer-login': typeof OrganizerLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/judge-login' | '/organizer-login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/judge-login' | '/organizer-login'
  id: '__root__' | '/' | '/judge-login' | '/organizer-login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JudgeLoginRoute: typeof JudgeLoginRoute
  OrganizerLoginRoute: typeof OrganizerLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge-login': {
      id: '/judge-login'
      path: '/judge-login'
      fullPath: '/judge-login'
      preLoaderRoute: typeof JudgeLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer-login': {
      id: '/organizer-login'
      path: '/organizer-login'
      fullPath: '/organizer-login'
      preLoaderRoute: typeof OrganizerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JudgeLoginRoute: JudgeLoginRoute,
  OrganizerLoginRoute: OrganizerLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
